# Generated by Django 5.1.6 on 2025-03-10 10:33

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_message', django_ckeditor_5.fields.CKEditor5Field()),
                ('full_message', django_ckeditor_5.fields.CKEditor5Field()),
                ('principal_image', models.ImageField(upload_to='principal/')),
                ('background_image', models.ImageField(upload_to='principal_bg/')),
            ],
        ),
    ]
