# Generated by Django 5.1.6 on 2025-04-30 10:06

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_homepagealert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagealert',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
