# Generated by Django 5.1.6 on 2025-08-08 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_homepagealert_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='notices/')),
            ],
        ),
    ]
