# Generated by Django 5.1.6 on 2025-08-08 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
