# Generated by Django 5.1.6 on 2025-03-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_principalmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principalmessage',
            name='background_image',
        ),
    ]
