# Generated by Django 5.1.6 on 2025-04-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_principalmessage_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('success', 'Exciting News (Green)'), ('error', 'Alert (Red)'), ('info', 'Information (Blue)')], default='info', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
