# Generated by Django 5.1.6 on 2025-08-08 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_notice_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
