# Generated by Django 5.1.6 on 2025-04-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0003_offeredprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='inter_timetables/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='timetable_previews/')),
            ],
        ),
        migrations.RemoveField(
            model_name='offeredprogram',
            name='image',
        ),
    ]
