# Generated by Django 5.1.6 on 2025-04-17 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0006_interexamination_remove_bstimetable_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BsExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='bs_timetables/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='timetable_previews/')),
            ],
        ),
    ]
