# Generated by Django 5.1.6 on 2025-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0009_department_department_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredprogram',
            name='roadmap',
            field=models.FileField(blank=True, null=True, upload_to='roadmaps/'),
        ),
    ]
