# Generated by Django 5.1.6 on 2025-07-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0010_offeredprogram_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredprogram',
            name='roadmap',
            field=models.FileField(default='default.pdf', upload_to='roadmaps/'),
            preserve_default=False,
        ),
    ]
