# Generated by Django 5.1.6 on 2025-08-09 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0012_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offeredprogram',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
