# Generated by Django 5.1.6 on 2025-04-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=50)),
                ('posted_date', models.DateField()),
                ('apply_by', models.DateField()),
                ('eligibility', models.TextField()),
                ('eligibility_criteria_url', models.URLField(blank=True, null=True)),
                ('details_url', models.URLField(blank=True, null=True)),
                ('eligibility_pdf_url', models.URLField(blank=True, null=True)),
                ('details_pdf_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Faculty', 'Faculty'), ('Staff', 'Staff')], max_length=20)),
            ],
        ),
    ]
