# Generated by Django 5.1.6 on 2025-04-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_apply_by_alter_job_job_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Administration', 'Administration'), ('Faculty', 'Faculty'), ('Staff', 'Staff')], max_length=20),
        ),
    ]
