# Generated by Django 5.1.6 on 2025-04-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faranian', '0002_newsbulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='magazines/covers/')),
                ('season', models.CharField(max_length=50)),
                ('posted_date', models.DateField()),
                ('description', models.TextField()),
                ('view_link', models.URLField()),
                ('pdf_file', models.FileField(upload_to='magazines/pdfs/')),
            ],
        ),
    ]
