# Generated by Django 5.1.6 on 2025-04-30 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faranian', '0003_magazine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='pdf_file',
            new_name='magzine',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='view_link',
        ),
        migrations.AlterField(
            model_name='magazine',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
