# Generated by Django 5.1.6 on 2025-04-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faranian', '0004_rename_pdf_file_magazine_magzine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='season',
        ),
    ]
