# Generated by Django 5.1.6 on 2025-08-09 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faranian', '0006_alter_magazine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
