# Generated by Django 5.1.6 on 2025-05-06 17:27

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='hod/')),
                ('hod_detail', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
    ]
