# Generated by Django 5.1.6 on 2025-08-09 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
