# Generated by Django 5.1.6 on 2025-04-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_alter_department_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
                ('total_seats', models.PositiveIntegerField()),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Both', 'Both')], max_length=10)),
                ('program_type', models.CharField(choices=[('Intermediate', 'Intermediate'), ('BS', 'BS')], max_length=20)),
            ],
        ),
    ]
