# Generated by Django 5.1.6 on 2025-04-17 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_bstimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='inter_timetables/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='timetable_previews/')),
            ],
        ),
        migrations.RemoveField(
            model_name='bstimetable',
            name='title',
        ),
        migrations.RemoveField(
            model_name='intertimetable',
            name='title',
        ),
        migrations.AlterField(
            model_name='bstimetable',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='intertimetable',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
