# Generated by Django 5.1.6 on 2025-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0007_bsexamination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsexamination',
            name='file',
            field=models.FileField(upload_to='bs_examinations/'),
        ),
        migrations.AlterField(
            model_name='bsexamination',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='examination_previews/'),
        ),
        migrations.AlterField(
            model_name='interexamination',
            name='file',
            field=models.FileField(upload_to='inter_examinations/'),
        ),
        migrations.AlterField(
            model_name='interexamination',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='examination_previews/'),
        ),
    ]
