# Generated by Django 5.1.6 on 2025-05-06 16:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0008_alter_bsexamination_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_detail',
            field=django_ckeditor_5.fields.CKEditor5Field(default='default-detail'),
            preserve_default=False,
        ),
    ]
