# Generated by Django 5.1.6 on 2025-08-06 10:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0011_alter_offeredprogram_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='administration/')),
                ('administration_detail', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
    ]
