# Generated by Django 5.1.6 on 2025-03-20 19:20

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='events/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
