# Generated by Django 5.1.6 on 2025-03-23 18:42

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_conference_alter_event_posted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='curricular_activities/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
