# Generated by Django 5.1.6 on 2025-04-30 09:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faranian', '0005_remove_magazine_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
