# Generated by Django 5.1.6 on 2025-03-23 18:18

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='conferences/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
