# Generated by Django 5.1.6 on 2025-04-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_salary_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='eligibility_criteria_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='eligibility_pdf_url',
        ),
    ]
