# Generated by Django 5.1.6 on 2025-04-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_eligibility_criteria_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='details_pdf_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='details_url',
        ),
        migrations.AddField(
            model_name='job',
            name='job_details',
            field=models.FileField(blank=True, null=True, upload_to='job_details/'),
        ),
    ]
