# Generated by Django 5.1.6 on 2025-04-29 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_details_pdf_url_remove_job_details_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_by',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_details',
            field=models.FileField(default='job_details/sample.pdf', upload_to='job_details/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
