# Generated by Django 5.1.6 on 2025-04-30 09:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='eligibility',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
